name: Run template tests

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@a2e0af7c20b84890b3a72de89c24c3382d6847fb  # v1.17.0
    with:
      envs: |
        - macos: py311-test
        - linux: py312-test
        - linux: py313-test
        - linux: build_docs

  bake_cookies:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@a2e0af7c20b84890b3a72de89c24c3382d6847fb  # v1.17.0
    with:
      artifact-path: |
        cookies
      envs: |
        - linux: bake_cookies
