name: Run template tests

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@86823142467dd2afcd1bbac57d3a664cf468eb3b  # v2.1.0
    with:
      envs: |
        - macos: py311-test
        - linux: py312-test
        - linux: py313-test
        - linux: build_docs

  bake_cookies:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@86823142467dd2afcd1bbac57d3a664cf468eb3b  # v2.1.0
    with:
      artifact-path: |
        cookies
      envs: |
        - linux: bake_cookies
